# @see https://gist.github.com/y0ssar1an/df2dab474520c4086926f672c52db139
dist: xenial

language: go

env:
  - GO111MODULE=on

go:
  - 1.11.x

git:
  depth: 1

notifications:
  email: false

install:
  - bash ./scripts/install.sh

script:
  - bash ./scripts/build.sh

deploy:
  provider: releases
  api_key:
    secure: dLXTsHWEmsNEGMc+xhPpLOtciZTuM2FlZWdEj8pRum9Eu+LTnUPDnTOFA3Vre0Hz7B0Ry71MRtwxUjvapk2WThtqf5m8iyAYygrjeOJ4jM4GCAhH0wB+kehSSAbvCZJSfwAb2iZqRAKKm1ha0axY/TF/oJIYbjVST7YLD7AkAVr9i4JRDvwBeUZXSQHeFvnC2CvmQVW9tjDiawMmxiALF2G4NpAS5IrtNfYCWjTx+bZxAWxWtUqE82txH5EOUjojIWZV+naqpXlWgCRub1Z7QNqY7/lNMq0/dz5XptLCwhQidLNQlcrj8OhMnOEu2VyQAK8D+rX30bEYTpd9RgIhM0RHWf5zBueWpvLTqexzlk9lnZAn3is8YfqFqVD787iMvXjXelyjC43t72pBoD7OcEJ0rNWmXe7critC1xVp5i70kdl7dLikFA+yXTdA7PZbPSF9H/3viFbl7t4SWt80Ms4I2Pv6vHyYwuEOfzZZFVFeuqYvxFW2puIXFON2+/tn9U+LN30aPLzXYlfY54JiwTz5+asfCMWZGOXGMfAC3SdKY0HSbcy1HWInQB/Si7hzHHriLyg1+TqFonk8Vv7VO5m3/yUzy2dSME+WDuohBrzQuNvaQOGe/6pm1sqWeyOX2/Bim5ehu5utuY/iV61EdryW2Zw5YESEWyy9kfjoTTo=
  file_glob: true
  file: bin/*
  skip_cleanup: true
  on:
    tags: true
